# Generated by Django 2.2 on 2019-08-24 07:26

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=50)),
                ('published_date', models.DateField(null=True)),
                ('publisher', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('book_description', models.CharField(max_length=1000)),
                ('book_image', models.ImageField(blank=True, upload_to=books.models.user_directory_path)),
            ],
        ),
    ]
